apiVersion: v1 
kind: Service
metadata: 
 name: mongodb-svc-headless
 namespace: roboshop
 labels:
  project: roboshop
  component: mongodb
  tier: database
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mongodb
    tier: database
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017