apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion }}"
        resources:
          requests:
           cpu: "50m"
           memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
         - configMapRef:
            name: user